# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"article_holder": "00_loadarticles.ipynb",
         "CoverageTrends": "00_loadarticles.ipynb",
         "describer": "01_descriptive_analysis.ipynb",
         "predicter": "02_predictive_analysis.ipynb"}

modules = ["loader.py",
           "describe.py",
           "predict.py"]

doc_url = "https://brockmanmatt.github.io/newstrends/"

git_url = "https://github.com/brockmanmatt/newstrends/tree/master/"

def custom_doc_links(name): return None
