# AUTOGENERATED! DO NOT EDIT! File to edit: 01_descriptive_analysis.ipynb (unless otherwise specified).

__all__ = ['describer']

# Cell
from newstrends import loader

# Cell
class describer:

    def __init__(self):
        self.loaded=False
        self.articleDir = ""


    def test():return True