# AUTOGENERATED! DO NOT EDIT! File to edit: 00_loadarticles.ipynb (unless otherwise specified).

__all__ = ['CoverageTrends', 'article_holder']

# Cell
import pandas as pd
import os, datetime

# Cell
def CoverageTrends(publications):
    return

# Cell
class article_holder:
    "Basic unit to keep load and analze my articles"

    def __init__(self):
        self.articleDir = None

    def set_articleDir(self, path): self.articleDir = path

    def get_articleDir(self): return self.articleDir

    def load_articles(self, engine=CoverageTrends, publications=[]):
        if self.articleDir == None:
            raise Exception("holder missing path")
            return
        self.df =